### ISSUE TITLE
Create Unit Tests Cases for Video_t.cpp

### ISSUE THREAD

**Issue by TJenks13** [TJenks13/StreamVideo-1#4]
We need to create a set of unit test cases for Video_t.cpp before refactoring the Video.cpp/.hpp files.

**Comment by TJenks13** [comment]
I added a test case to test for a movie and movie output.

**Comment by jat113** [comment]
Create a pull request and pull it in when you're ready.

**Comment by jat113** [comment]
I pulled it in for you.

**Comment by jat113** [comment]
So I will close this

**Comment by TJenks13** [comment]
I wasn't finished working on it, so I hadn't pulled it yet. Please do not pull in things I am working on.

**Comment by TJenks13** [comment]
I'll close it out and start a new issue/branch so I can finish the test cases I was going to do and start on a few other refactors.
